complexity:
  LongParameterList:
    active: false
  TooManyFunctions:
    excludes: &excludePatterns
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
      - '**/generated/**'
      - '**/build/**'
  LargeClass:
    excludes: *excludePatterns


    exceptions:
      TooGenericExceptionCaught:
        active: true
        excludes: *excludePatterns
        exceptionNames:
          - 'Error'
          - 'RuntimeException'
          - 'Throwable'
        allowedExceptionNameRegex: '_|(ignore|expected).*'
      SwallowedException:
        excludes: *excludePatterns

    naming:
      FunctionNaming:
        functionPattern: '([A-Za-z][a-zA-Z0-9]*)|(`.*)'
      ClassNaming:
        excludes: *excludePatterns
      FunctionParameterNaming:
        excludes: *excludePatterns
      ConstructorParameterNaming:
        excludes: *excludePatterns

    empty-blocks:
      EmptyClassBlock:
        excludes: *excludePatterns
      EmptyFunctionBlock:
        excludes: *excludePatterns

    formatting:
      CommentSpacing:
        active: false
      NoLineBreakBeforeAssignment:
        excludes: *excludePatterns
      NoUnusedImports:
        excludes: *excludePatterns
      ParameterListWrapping:
        excludes: *excludePatterns
      SpacingAroundColon:
        excludes: *excludePatterns
      SpacingAroundCurly:
        excludes: *excludePatterns
      NoUnitReturn:
        excludes: *excludePatterns
      NoConsecutiveBlankLines:
        excludes: *excludePatterns
      NoTrailingSpaces:
        excludes: *excludePatterns
      MaximumLineLength:
        excludes: *excludePatterns
      SpacingAroundKeyword:
        excludes: *excludePatterns
      NoBlankLineBeforeRbrace:
        excludes: *excludePatterns
      SpacingAroundParens:
        excludes: *excludePatterns
      NoEmptyClassBody:
        excludes: *excludePatterns
      Indentation:
        excludes: *excludePatterns
      ImportOrdering:
        excludes: *excludePatterns
      NoMultipleSpaces:
        excludes: *excludePatterns
      Wrapping:
        excludes: *excludePatterns
      ArgumentListWrapping:
        active: false
      NoEmptyFirstLineInMethodBlock:
        active: false
      Filename:
        active: false
      SpacingBetweenDeclarationsWithAnnotations:
        active: false
      FunctionReturnTypeSpacing:
        excludes: *excludePatterns
      NoSemicolons:
        excludes: *excludePatterns

    style:
      ForbiddenComment:
        active: true
        comments:
          - 'FIXME:'
          - 'STOPSHIP:'
        allowedPatterns: 'TODO:'
      MagicNumber:
        excludes: *excludePatterns
        ignorePropertyDeclaration: true
        ignoreCompanionObjectPropertyDeclaration: true
      MaxLineLength:
        excludes: *excludePatterns
      MayBeConst:
        excludes: *excludePatterns
      UnusedPrivateMember:
        excludes: *excludePatterns
      UnusedPrivateProperty:
        excludes: *excludePatterns